am config

diff --git a/forgerock-am/Dockerfile b/forgerock-am/Dockerfile
--- a/forgerock-am/Dockerfile
+++ b/forgerock-am/Dockerfile
@@ -1,7 +1,7 @@
 FROM debian:stable-slim
 
-ADD _binaries/amster.zip /
-ADD _binaries/am.war /
+ADD forgerock-am/_binaries/amster.zip /
+ADD forgerock-am/_binaries/am.war /
 
 RUN apt-get update && \
     apt-get install --no-install-recommends -y unzip && \
@@ -15,6 +15,8 @@ FROM tomcat:9-jre11-slim
 SHELL ["/bin/bash", "-c"]
 ENV FORGEROCK_HOME /home/forgerock
 ENV OPENAM_HOME /home/forgerock/openam
+ENV OB_DOMAIN dev-ob.forgerock.financial
+ENV CATALINA_OPTS "-Xms2048m -Xmx2048m"
 
 RUN rm -fr "$CATALINA_HOME"/webapps/*
 COPY --from=0 /var/tmp/openam "$CATALINA_HOME"/webapps/ROOT
@@ -23,7 +25,7 @@ COPY --from=0 /var/tmp/amster /opt/amster
 ADD https://github.com/krallin/tini/releases/download/v0.18.0/tini /usr/bin
 
 RUN apt-get update && \
-    apt-get install --no-install-recommends -y unzip curl bash procps && \
+    apt-get install --no-install-recommends -y unzip curl bash procps openssh-client && \
     chmod +x /usr/bin/tini && \
     addgroup --gid 11111 forgerock && \
     adduser --shell /bin/bash --home "$FORGEROCK_HOME" --uid 11111 --disabled-password --ingroup root --gecos 'forgerock' forgerock && \
@@ -32,21 +34,35 @@ RUN apt-get update && \
     chown -R forgerock:root  "$FORGEROCK_HOME" && \
     chmod -R g+rwx "$CATALINA_HOME"
 
-RUN export CATALINA_OPTS="-Xmx1024m -Xms1024m " && \
-    export OB_DOMAIN="dev-ob.forgerock.financial" && \
+ADD keystore/ca/*.crt /home/forgerock/
+COPY  forgerock-am/am/server.xml "$CATALINA_HOME"/conf/server.xml
+ADD keystore/common/keystore.jks /etc/ssl/certs/java/keystore.jks
+
+RUN mkdir -p /var/run/secrets/amster && \
+    ssh-keygen -t rsa -b 4096 -C "obri-amster@example.com" -f /var/run/secrets/amster/id_rsa -q -N "" && \
+    keytool -import -alias obri-internal-ca -trustcacerts -noprompt \
+            -keystore /etc/ssl/certs/java/cacerts -storepass changeit \
+            -file /home/forgerock/obri-internal-ca.crt && \
+    keytool -import -alias obri-external-ca -trustcacerts -noprompt \
+            -keystore /etc/ssl/certs/java/cacerts -storepass changeit \
+            -file /home/forgerock/obri-external-ca.crt
+
+ADD forgerock-am/amster/ /opt/amster/
+ADD forgerock-am/am/*.sh $FORGEROCK_HOME/
+
+RUN echo "127.0.0.1  openam" >> /etc/hosts && \
     /usr/local/tomcat/bin/catalina.sh start && \
     tail -f /usr/local/tomcat/logs/catalina.out | while read LOGLINE; do \
         echo "${LOGLINE}"; \
         [[ "${LOGLINE}" == *"Server startup in"* ]] && pkill -P $$ tail; \
     done && \
     cd /opt/amster && \
-    /opt/amster/amster-install.sh | tee /amster.log && \
-    if grep "Failed to import\|IMPORT ERRORS\|SCRIPT ERROR" /amster.log; then echo "ABORTING BUILD DUE TO ERRORS." && exit 10; fi && \
+    set -euo pipefail && \
+    /opt/amster/amster-install.sh |& tee /amster.log && \
+    if grep -q "Failed to\|IMPORT ERRORS\|SCRIPT ERROR\|Exception\|Configuration failed" /amster.log; then echo "ABORTING BUILD DUE TO AMSTER ERRORS." && exit 10; fi && \
+    echo "Shutting down tomcat" && \
     /usr/local/tomcat/bin/catalina.sh stop && \
     sleep 10
 
-#TODO: add amster scripts, amster-install.sh
-#TODO: simple amster config
-#TODO: Do we need to create the OUs in the embedded DS for the different realms?
-#TODO: entrypoint script
-#TODO: Does AM need to run on SSL?
+ENTRYPOINT ["/home/forgerock/docker-entrypoint.sh"]
+CMD ["run"]
