925: AM 6.5.1 security patch 202204 - Upgraded to use the new openam 6.5.1 patched with 202204 security advisor Issue: https://github.com/ForgeCloud/ob-deploy/issues/925 Relevant comment: https://github.com/ForgeCloud/ob-deploy/issues/925#issuecomment-1310519670

diff --git a/forgerock-am/Dockerfile b/forgerock-am/Dockerfile
--- a/forgerock-am/Dockerfile
+++ b/forgerock-am/Dockerfile
@@ -12,8 +12,8 @@ RUN apt-get update && \
     apt-get install --no-install-recommends -y unzip && \
     mkdir -p /var/tmp/openam && \
     unzip -q /am.war -d /var/tmp/openam && \
-    if ! grep -q "com.iplanet.am.buildVersion=ForgeRock Access Management 6.5.5" /var/tmp/openam/WEB-INF/classes/serverdefaults.properties; then \
-    echo "ERROR: Provided war file is not AM version 6.5.5" && \
+    if ! grep -q "com.iplanet.am.buildVersion=ForgeRock Access Management 6.5.1" /var/tmp/openam/WEB-INF/classes/serverdefaults.properties; then \
+    echo "ERROR: Provided war file is not AM version 6.5.1" && \
     echo "VERSION FOUND: $(grep 'com.iplanet.am.buildVersion=' /var/tmp/openam/WEB-INF/classes/serverdefaults.properties)" && \
     exit 10; \
     fi && \
